#!/usr/bin/env python3
"""Deploy difftastic (and delta, when installed) as opt-in git diff viewers.

Nothing here changes what plain `git diff` emits for scripts and agents: difftastic is reached
only through explicit aliases (`git dft`, `git ddiff`, `git dlog`, `git dshow`), and delta is a
pager, which git only starts for a terminal. Everything is written to one include file
(~/.config/git/wf-diff.gitconfig) that ~/.gitconfig pulls in, so it is regenerated
deterministically and removed with `remove`. Gated by `gitDiff.enabled` in the home config
layer. Stdlib only — see wf_config.py for why.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import wf_config  # noqa: E402

OK = 0
ERR_DISABLED = 1
ERR_CONFLICT = 2
ERR_INSTALL = 3
ERR_CONFIG = 4

REPO = "Wilfred/difftastic"
DOWNLOAD_TIMEOUT = 60
GIT_TIMEOUT = 10

HEADER = """\
# Generated by the core workflows plugin (skill: setup-git-diff). Do not edit by hand.
# Source: plugins/core/scripts/wf_gitdiff_setup.py
# Regenerate: /core:setup-git-diff, or `wf_gitdiff_setup.py apply`. Remove: `wf_gitdiff_setup.py remove`.
"""


# --------------------------------------------------------------------------- config


def cfg(merged: dict, key: str, default):
    value, found = wf_config.lookup(merged, key)
    return value if found else default


def load_settings() -> dict:
    """Read only the plugin and home layers: a global git setup must not be switched on by
    whichever repository this happens to run from."""
    layers = wf_config.layer_paths()
    merged, _ = wf_config.merge_layers(
        [(name, wf_config.read_layer(layers[name])) for name in ("plugin", "home")]
    )
    return {
        "enabled": bool(cfg(merged, "gitDiff.enabled", False)),
        "difftastic": bool(cfg(merged, "gitDiff.difftastic.enabled", True)),
        "version": str(cfg(merged, "gitDiff.difftastic.version", "latest")),
        "install_dir": Path(str(cfg(merged, "gitDiff.difftastic.installDir", "~/.local/bin")))
        .expanduser(),
        "delta": bool(cfg(merged, "gitDiff.delta.enabled", True)),
        "home_config": layers["home"],
    }


# --------------------------------------------------------------------------- paths


def include_file() -> Path:
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(base) / "git" / "wf-diff.gitconfig"


def include_ref(path: Path) -> str:
    """The include.path value: ~-relative when under $HOME so the config survives a rename."""
    try:
        return "~/" + path.relative_to(Path.home()).as_posix()
    except ValueError:
        return str(path)


def find_difft(settings: dict) -> str | None:
    found = shutil.which("difft")
    if found:
        return found
    candidate = settings["install_dir"] / "difft"
    return str(candidate) if candidate.is_file() and os.access(candidate, os.X_OK) else None


# --------------------------------------------------------------------------- gitconfig content


def alias_value(git_args: str, display: str) -> str:
    # `!` aliases start in the repo root; GIT_PREFIX restores the caller's directory so relative
    # path arguments still work. `core.pager=less` keeps a line-oriented pager (e.g. delta) from
    # being fed difftastic's non-patch output.
    return (
        f'!f() {{ cd "${{GIT_PREFIX:-.}}" && GIT_EXTERNAL_DIFF=difft DFT_DISPLAY={display} '
        f'git -c core.pager=less {git_args} --ext-diff "$@"; }}; f'
    )


def desired_entries(use_difft: bool, use_delta: bool) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    if use_difft:
        entries += [
            ("alias.dft", alias_value("diff", "side-by-side")),
            ("alias.ddiff", alias_value("diff", "inline")),
            ("alias.dlog", alias_value("log -p", "side-by-side")),
            ("alias.dshow", alias_value("show", "side-by-side")),
        ]
    if use_delta:
        entries += [
            ("core.pager", "delta"),
            ("interactive.diffFilter", "delta --color-only"),
            ("delta.navigate", "true"),
            ("delta.line-numbers", "true"),
        ]
    return entries


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_include(entries: list[tuple[str, str]]) -> str:
    lines = [HEADER]
    section = None
    for dotted, value in entries:
        name, _, key = dotted.partition(".")
        if name != section:
            lines.append(f"[{name}]")
            section = name
        lines.append(f"\t{key} = {quote(value)}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- git plumbing


def git_global(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "config", "--global", *args], capture_output=True, text=True, timeout=GIT_TIMEOUT
    )


def existing_values(key: str) -> list[str]:
    """Values `key` already has in the global config file itself. `git config --global` does not
    follow includes, so our own include file never shows up here."""
    out = git_global("--get-all", key)
    return out.stdout.splitlines() if out.returncode == 0 else []


def is_included(ref: str) -> bool:
    out = git_global("--get-all", "include.path")
    return out.returncode == 0 and ref in out.stdout.splitlines()


# --------------------------------------------------------------------------- difftastic install


def target_triple() -> str:
    machine = {"x86_64": "x86_64", "amd64": "x86_64", "aarch64": "aarch64", "arm64": "aarch64"}.get(
        platform.machine().lower()
    )
    system = platform.system()
    if machine and system == "Linux":
        return f"{machine}-unknown-linux-gnu"
    if machine and system == "Darwin":
        return f"{machine}-apple-darwin"
    raise RuntimeError(f"no prebuilt difftastic for {system}/{platform.machine()}; use cargo")


def resolve_version(requested: str) -> str:
    if requested != "latest":
        return requested
    url = f"https://api.github.com/repos/{REPO}/releases/latest"
    with urllib.request.urlopen(url, timeout=DOWNLOAD_TIMEOUT) as response:
        return json.load(response)["tag_name"]


def install_difft(settings: dict) -> str:
    version = resolve_version(settings["version"])
    asset = f"difft-{version}-{target_triple()}.tar.gz"
    url = f"https://github.com/{REPO}/releases/download/{version}/{asset}"
    print(f"downloading {url}")
    dest_dir: Path = settings["install_dir"]
    dest_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        archive = Path(tmp) / asset
        with urllib.request.urlopen(url, timeout=DOWNLOAD_TIMEOUT) as response:
            archive.write_bytes(response.read())
        with tarfile.open(archive) as tar:
            member = next(
                (m for m in tar.getmembers() if m.isfile() and Path(m.name).name == "difft"), None
            )
            if member is None:
                raise RuntimeError(f"{asset} contains no 'difft' binary")
            staged = dest_dir / ".difft.new"
            staged.write_bytes(tar.extractfile(member).read())  # type: ignore[union-attr]
    staged.chmod(0o755)
    os.replace(staged, dest_dir / "difft")
    return str(dest_dir / "difft")


# --------------------------------------------------------------------------- commands


def plan(settings: dict) -> tuple[str | None, str | None, list[tuple[str, str]]]:
    difft = find_difft(settings) if settings["difftastic"] else None
    delta = shutil.which("delta") if settings["delta"] else None
    return difft, delta, desired_entries(bool(difft), bool(delta))


def cmd_show(_: argparse.Namespace) -> int:
    settings = load_settings()
    difft, delta, entries = plan(settings)
    print(f"# gitDiff.enabled = {settings['enabled']}")
    print(f"# difft: {difft or 'not installed (apply would download it)'}")
    print(f"# delta: {delta or 'not installed (pager settings skipped; sudo apt install git-delta)'}")
    print(f"# include file: {include_file()}\n")
    print(render_include(entries), end="")
    return OK


def cmd_status(_: argparse.Namespace) -> int:
    settings = load_settings()
    difft, delta, entries = plan(settings)
    path = include_file()
    print(f"enabled:   {settings['enabled']}")
    print(f"difft:     {difft or 'MISSING'}")
    print(f"delta:     {delta or 'MISSING'}")
    print(f"included:  {is_included(include_ref(path))}")
    if not path.is_file():
        print("include:   absent")
    elif path.read_text(encoding="utf-8") == render_include(entries):
        print("include:   in sync")
    else:
        print("include:   DRIFTED — rerun apply")
    if difft and not shutil.which("difft"):
        print(f"warning: {settings['install_dir']} is not on PATH; aliases need `difft` on PATH")
    return OK


def cmd_apply(args: argparse.Namespace) -> int:
    settings = load_settings()
    if not settings["enabled"]:
        print(
            "gitDiff.enabled is false. Opt this machine in first:\n"
            f'  {settings["home_config"]}  ->  {{"gitDiff": {{"enabled": true}}}}',
            file=sys.stderr,
        )
        return ERR_DISABLED

    difft = find_difft(settings) if settings["difftastic"] else None
    if settings["difftastic"] and (args.upgrade or (not difft and not args.no_install)):
        try:
            difft = install_difft(settings)
        except (OSError, RuntimeError, urllib.error.URLError, KeyError, tarfile.TarError) as exc:
            print(f"error: difftastic install failed: {exc}", file=sys.stderr)
            return ERR_INSTALL
    if settings["difftastic"] and not difft:
        print("note: difft not installed; aliases skipped (drop --no-install to fetch it)")

    delta = shutil.which("delta") if settings["delta"] else None
    if settings["delta"] and not delta:
        # core.pager=delta with no delta on PATH would break every paged git command.
        print("note: delta not installed; pager settings skipped. Install it, then rerun:")
        print("      sudo apt install git-delta   (or: brew install git-delta)")

    entries = desired_entries(bool(difft), bool(delta))
    path = include_file()
    conflicts = {
        key: values
        for key, value in entries
        if (values := [v for v in existing_values(key) if v != value])
    }
    if conflicts and not args.force:
        print("error: ~/.gitconfig already sets keys this would manage:", file=sys.stderr)
        for key, values in conflicts.items():
            print(f"  {key} = {values[0]}", file=sys.stderr)
        print("Remove them, or pass --force to add the include anyway.", file=sys.stderr)
        return ERR_CONFLICT

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_include(entries), encoding="utf-8")
    ref = include_ref(path)
    if not is_included(ref):
        added = git_global("--add", "include.path", ref)
        if added.returncode != 0:
            print(f"error: could not update ~/.gitconfig: {added.stderr.strip()}", file=sys.stderr)
            return ERR_CONFIG
    print(f"wrote {path} and included it from the global git config")
    if difft and not shutil.which("difft"):
        print(f"warning: {settings['install_dir']} is not on PATH; add it so `git dft` finds difft")
    return OK


def cmd_remove(_: argparse.Namespace) -> int:
    path = include_file()
    ref = include_ref(path)
    if is_included(ref):
        git_global("--fixed-value", "--unset-all", "include.path", ref)
    if path.is_file():
        path.unlink()
    print("removed the include and its file (the difft binary is left in place)")
    return OK


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="wf_gitdiff_setup.py", description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("show", help="print what apply would write").set_defaults(func=cmd_show)
    sub.add_parser("status", help="report tools, include and drift").set_defaults(func=cmd_status)

    apply_ = sub.add_parser("apply", help="install difft if needed and write the git config")
    apply_.add_argument("--force", action="store_true", help="add the include despite conflicts")
    apply_.add_argument("--no-install", action="store_true", help="never download difft")
    apply_.add_argument("--upgrade", action="store_true", help="re-download difft")
    apply_.set_defaults(func=cmd_apply)

    sub.add_parser("remove", help="drop the include and delete its file").set_defaults(
        func=cmd_remove
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return args.func(args)
    except wf_config.ConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return ERR_CONFIG


if __name__ == "__main__":
    sys.exit(main())
